-- QUESTION#1 Create a Fiction table with structure show in Figure 6-29

CREATE TABLE FICTION
(BOOK_CODE CHAR(4) PRIMARY KEY,
TITLE CHAR(40),
PUBLISHER_CODE CHAR(3),
PRICE DECIMAL(4,2)
); 

-- QUESTION#2
INSERT INTO FICTION
SELECT BOOK_CODE, TITLE, PUBLISHER_CODE, PRICE
FROM BOOK
WHERE TYPE = 'FIC';